spring.application.name=mini-dish-api
spring.datasource.url=jdbc:postgresql://localhost:5432/mini_dish_db
spring.datasource.username=mini_dish_db_manager
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8080

# Désactiver l'init SQL automatique de Spring Boot
spring.sql.init.mode=never
